# -*- coding: utf-8 -*-
"""
Created on Wed Aug  4 10:47:30 2021

@author: Porco Rosso
"""
from numpy import nan
import pandas as pd

df = {
     0: {'source_key': 'id', 'save_key': 'id_key', 'data_type': 'int', 'comment': '来源自增id'},
     1: {'source_key': 'code', 'save_key': 's_info_windcode', 'data_type': 'varchar(12)', 'comment': '股票代码\n'},
     2: {'source_key': 'a_code', 'save_key': nan, 'data_type': 'varchar(12)', 'comment': 'A股代码\n'},
     3: {'source_key': 'b_code', 'save_key': nan, 'data_type': 'varchar(12)', 'comment': 'B股代码\n'},
     4: {'source_key': 'h_code', 'save_key': nan, 'data_type': 'varchar(12)', 'comment': 'H股代码\n'},
     5: {'source_key': 'pub_date', 'save_key': 'ann_dt', 'data_type': 'datetime', 'comment': '公告日期\n'},
     6: {'source_key': 'end_date', 'save_key': nan, 'data_type': 'datetime', 'comment': '截止日期\n'},
     7: {'source_key': 'report_date', 'save_key': 'report_period', 'data_type': 'datetime', 'comment': '报告期\n'},
     8: {'source_key': 'report_type', 'save_key': nan, 'data_type': 'int', 'comment': '报告期类型\n'},
     10: {'source_key': 'source', 'save_key': nan, 'data_type': 'varchar(60)', 'comment': '报表来源\n'},
     11: {'source_key': 'cash_equivalents', 'save_key': 'monetary_cap', 'data_type': 'decimal(20,4)', 'comment': '货币资金\n货币资金是指在企业生产经营过程中处于货币形态的那部分资金，按其形态和用途不同可分为包括库存现金、银行存款和其他货币资金。它是企业中最活跃的资金，流动性强，是企业的重要支付手段和流通手段，因而是流动资产的审查重点。货币资金：又称为货币资产，是指在企业生产经营过程中处于货币形态的资产。是指可以立即投入流通，用以购买商品或劳务或用以偿还债务的交换媒介物。'},
     12: {'source_key': 'trading_assets', 'save_key': 'tradable_fin_assets', 'data_type': 'decimal(20,4)', 'comment': '交易性金融资产\n交易性金融资产是指：企业为了近期内出售而持有的金融资产。通常情况下，以赚取差价为目的从二级市场购入的股票、债券和基金等，应分类为交易性金融资产，故长期股权投资不会被分类转入交易性金融资产及其直接指定为以公允价值计量且其变动计入当期损益的金融资产进行核算。'},
     13: {'source_key': 'bill_receivable', 'save_key': 'notes_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收票据\n应收票据是指企业持有的还没有到期、尚未兑现的票据。应收票据是企业未来收取货款的权利，这种权利和将来应收取的货款金额以书面文件形式约定下来，因此它受到法律的保护，具有法律上的约束力。是一种债权凭证。根据我国现行法律的规定，商业汇票的期限不得超过6个月，因而我国的商业汇票是一种流动资产。在我国应收票据、应付票据通常是指“商业汇票”，包括“银行承兑汇票”和“商业承兑汇票”两种，是远期票据，付款期一般在1个月以上，6个月以内。其他的银行票据(支票、本票、汇票}等，都是作为货币资金来核算的，而不作为应收应付票据'},
     14: {'source_key': 'account_receivable', 'save_key': 'acct_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收账款\n应收账款是指企业在正常的经营过程中因销售商品、产品、提供劳务等业务，应向购买单位收取的款项，包括应由购买单位或接受劳务单位负担的税金、代购买方垫付的各种运杂费等。'},
     15: {'source_key': 'advance_payment', 'save_key': 'prepay', 'data_type': 'decimal(20,4)', 'comment': '预付款项\n预付款项，包括预付货款和预付工程款等，通常属于流动资产。预付账款与应收账款都属于公司的债权，但两者产生的原因不同，应收账款是公司应收的销货款，通常是用货币清偿的，而预付账款是预付给供货单位的购货款或预付给施工单位的工程价款和材料款，通常是用商品、劳务或完工工程来清偿的。'},
     16: {'source_key': 'other_receivable', 'save_key': 'oth_rcv', 'data_type': 'decimal(20,4)', 'comment': '其他应收款\n其他应收款是企业应收款项的另一重要组成部分。是企业除应收票据、应收账款和预付账款以外的各种应收暂付款项。其他应收款通常包括暂付款，是指企业在商品交易业务以外发生的各种应收、暂付款项。'},
     17: {'source_key': 'affiliated_company_receivable', 'save_key': 'aff_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收关联公司款\n'},
     18: {'source_key': 'interest_receivable', 'save_key': 'int_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收利息\n应收利息是指：短期债券投资实际支付的价款中包含的已到付息期但尚未领取的债券利息。这部分应收利息不计入短期债券投资初始投资成本中。但实际支付的价款中包含尚未到期的债券利息，则计入短期债券投资初始投资成本中（不需要单独核算）。'},
     19: {'source_key': 'dividend_receivable', 'save_key': 'dvd_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收股利\n应收股利是指企业因股权投资而应收取的现金股利以及应收其他单位的利润，包括企业购入股票实际支付的款项中所包括的已宣告发放但尚未领取的现金股利和企业因对外投资应分得的现金股利或利润等，但不包括应收的股票股利。'},
     20: {'source_key': 'inventories', 'save_key': 'inventories', 'data_type': 'decimal(20,4)', 'comment': '存货\n是指企业在日常活动中持有的以备出售的产成品或商品、处在生产过程中的在产品、在生产过程或提供劳务过程中耗用的材料和物料等。'},
     21: {'source_key': 'expendable_biological_asset', 'save_key': 'consumptive_bio_assets', 'data_type': 'decimal(20,4)', 'comment': '消耗性生物资产\n'},
     22: {'source_key': 'non_current_asset_in_one_year', 'save_key': 'non_cur_assets_due_within_1y', 'data_type': 'decimal(20,4)', 'comment': '一年内到期的非流动资产\n一年内到期的非流动资产反映企业将于一年内到期的非流动资产项目金额。包括一年内到期的持有至到期投资、长期待摊费用和一年内可收回的长期应收款。应根据有关科目的期末余额填列。执行企业会计制度的企业根据“一年内到期的长期债权投资”等科目填列。'},
     23: {'source_key': 'total_current_assets', 'save_key': 'tot_cur_assets', 'data_type': 'decimal(20,4)', 'comment': '流动资产合计\n指在一年内或者超过一年的一个营业周期内变现或者耗用的资产，包括货币资金、短期投资、应收票据、应收账款、坏账准备、应收账款净额、预付账款、其他应收款、存货、待转其他业务支出、待摊费用、待处理流动资产净损失、一年内到期的长期债券投资、其他流动资产等项。'},
     24: {'source_key': 'hold_for_sale_assets', 'save_key': 'fin_assets_avail_for_sale', 'data_type': 'decimal(20,4)', 'comment': '可供出售金融资产\n可供出售金融资产指初始确认时即被指定为可供出售的非衍生金融资产，以及下列各类资产之外的非衍生金融资产：（一）贷款和应收款项；（二）持有至到期投资；（三）交易性金融资产。'},
     25: {'source_key': 'hold_to_maturity_investments', 'save_key': 'held_to_mty_invest', 'data_type': 'decimal(20,4)', 'comment': '持有至到期投资\n持有至到期投资指企业有明确意图并有能力持有至到期，到期日固定、回收金额固定或可确定的非衍生金融资产。以下非衍生金融资产不应划分为持有至到期投资：（一）初始确认时划分为交易性非衍生金融资产；（二）初始确认时被指定为可供出售非衍生金融资产；（三）符合贷款和应收款项定义的非衍生金融资产。'},
     26: {'source_key': 'longterm_receivable_account', 'save_key': 'long_term_rec', 'data_type': 'decimal(20,4)', 'comment': '长期应收款\n长期应收款是根据长期应收款的账户余额减去未确认融资收益还有一年内到期的长期应收款。'},
     27: {'source_key': 'longterm_equity_invest', 'save_key': 'long_term_eqy_invest', 'data_type': 'decimal(20,4)', 'comment': '长期股权投资\n长期股权投资是指企业持有的对其子公司、合营企业及联营企业的权益性投资以及企业持有的对被投资单位不具有控制、共同控制或重大影响，且在活跃市场中没有报价、公允价值不能可靠计量的权益性投资。'},
     28: {'source_key': 'investment_property', 'save_key': 'invest_real_estate', 'data_type': 'decimal(20,4)', 'comment': '投资性房地产\n投资性房地产是指为赚取租金或资本增值，或两者兼有而持有的房地产。投资性房地产应当能够单独计量和出售。'},
     29: {'source_key': 'fixed_assets', 'save_key': 'fix_assets', 'data_type': 'decimal(20,4)', 'comment': '固定资产\n固定资产是指企业为生产商品、提供劳务、出租或经营管理而持有的、使用寿命超过一个会计年度的有形资产。属于产品生产过程中用来改变或者影响劳动对象的劳动资料，是固定资本的实物形态。固定资产在生产过程中可以长期发挥作用，长期保持原有的实物形态，但其价值则随着企业生产经营活动而逐渐地转移到产品成本中去，并构成产品价值的一个组成部分。'},
     30: {'source_key': 'constru_in_process', 'save_key': 'const_in_prog', 'data_type': 'decimal(20,4)', 'comment': '在建工程\n在建工程是指企业固定资产的新建、改建、扩建，或技术改造、设备更新和大修理工程等尚未完工的工程支出。在建工程通常有”自营”和”出包”两种方式。自营在建工程指企业自行购买工程用料、自行施工并进行管理的工程；出包在建工程是指企业通过签订合同，由其它工程队或单位承包建造的工程。'},
     31: {'source_key': 'construction_materials', 'save_key': 'proj_matl', 'data_type': 'decimal(20,4)', 'comment': '工程物资\n工程物资是指用于固定资产建造的建筑材料（如钢材、水泥、玻璃等），企业（民用航空运输）的高价周转件（例如飞机的引擎）等。买回来要再次加工建设的资产。在资产负债表中列示为非流动资产。'},
     32: {'source_key': 'fixed_assets_liquidation', 'save_key': 'fix_assets_disp', 'data_type': 'decimal(20,4)', 'comment': '固定资产清理\n固定资产清理是指企业因出售、报废和毁损等原因转入清理的固定资产价值及其在清理过程中所发生的清理费用和清理收入等。'},
     33: {'source_key': 'biological_assets', 'save_key': 'productive_bio_assets', 'data_type': 'decimal(20,4)', 'comment': '生产性生物资产\n生产性生物资产是指为产出农产品、提供劳务或出租等目的而持有的生物资产，包括经济林、薪炭林、产畜和役畜等。'},
     34: {'source_key': 'oil_gas_assets', 'save_key': 'oil_and_natural_gas_assets', 'data_type': 'decimal(20,4)', 'comment': '油气资产\n重要资产，其价值在总资产中占有较大比重。油气资产是指油气开采企业所拥有或控制的井及相关设施和矿区权益。油气资产属于递耗资产。递耗资产是通过开掘、采伐、利用而逐渐耗竭，以致无法恢复或难以恢复、更新或按原样重置的自然资源，如矿藏、原始森林等。油气资产是油气生产企业的重要资产，其价值在总资产中占有较大比重。'},
     35: {'source_key': 'intangible_assets', 'save_key': 'intang_assets', 'data_type': 'decimal(20,4)', 'comment': '无形资产\n无形资产是指企业拥有或者控制的没有实物形态的可辨认非货币性资产。资产满足下列条件之一的，符合无形资产定义中的可辨认性标准：\u30001、能够从企业中分离或者划分出来，并能够单独或者与相关合同、资产或负债一起，用于出售、转移、授予许可、租赁或者交换。\u30002、源自合同性权利或其他法定权利，无论这些权利是否可以从企业或其他权利和义务中转移或者分离。无形资产主要包括专利权、非专利技术、商标权、著作权、土地使用权、特许权等。商誉的存在无法与企业自身分离，不具有可辨认性，不属于本章所指无形资产。'},
     36: {'source_key': 'development_expenditure', 'save_key': 'r_and_d_costs', 'data_type': 'decimal(20,4)', 'comment': '开发支出\n开发支出项目是反映企业开发无形资产过程中能够资本化形成无形资产成本的支出部分。开发支出项目应当根据”研发支出”科目中所属的”资本化支出”明细科目期末余额填列。'},
     37: {'source_key': 'good_will', 'save_key': 'goodwill', 'data_type': 'decimal(20,4)', 'comment': '商誉\n商誉是指能在未来期间为企业经营带来超额利润的潜在经济价值，或一家企业预期的获利能力超过可辨认资产正常获利能力（如社会平均投资回报率）的资本化价值。商誉是企业整体价值的组成部分。在企业合并时，它是购买企业投资成本超过被并企业净资产公允价值的差额。'},
     38: {'source_key': 'long_deferred_expense', 'save_key': 'long_term_deferred_exp', 'data_type': 'decimal(20,4)', 'comment': '长期待摊费用\n长期待摊费用是指企业已经支出，但摊销期限在1年以上(不含1年)的各项费用，包括开办费、租入固定资产的改良支出及摊销期在1年以上的固定资产大修理支出、股票发行费用等。应由本期负担的借款利息、租金等，不得作为长期待摊费用。'},
     39: {'source_key': 'deferred_tax_assets', 'save_key': 'deferred_tax_assets', 'data_type': 'decimal(20,4)', 'comment': '递延所得税资产\n指对于可抵扣暂时性差异，以未来期间很可能取得用来抵扣可抵扣暂时性差异的应纳税所得额为限确认的一项资产。而对于所有应纳税暂时性差异均应确认为一项递延所得税负债，但某些特殊情况除外。递延所得税资产和递延所得税负债是和暂时性差异相对应的，可抵减暂时性差异是将来可用来抵税的部分，是应该收回的资产，所以对应递延所得税资产递延所得税负债是由应纳税暂时性差异产生的，对于影响利润的暂时性差异，确认的递延所得税负债应该调整“所得税费用”。例如会计折旧小于税法折旧，导致资产的账面价值大于计税基础，如果产品已经对外销售了，就会影响利润，所以递延所得税负债应该调整当期的所得税费用。如果暂时性差异不影响利润，而是直接计入所有者权益的，则确认的递延所得税负债应该调整资本公积。例如可供出售金融资产是按照公允价值来计量的，公允价值产升高了，会计上调增了可供出售金融资产的账面价值，并确认的资本公积，因为不影响利润，所以确认的递延所得税负债不能调整所得税费用，而应该调整资本公积。'},
     40: {'source_key': 'total_non_current_assets', 'save_key': 'tot_non_cur_assets', 'data_type': 'decimal(20,4)', 'comment': '非流动资产合计\n公式：非流动资产合计=所有的非流动资产项目之和—一年内到期的非流动资产=固定资产—累计折旧—固定资产减值准备—一年内到期的非流动资产。'},
     41: {'source_key': 'total_assets', 'save_key': 'tot_assets', 'data_type': 'decimal(20,4)', 'comment': '资产总计\n资产总计是指企业拥有或可控制的能以货币计量的经济资源，包括各种财产、债权和其他权利。企业的资产按其流动性划分为：流动资产、长期投资、固定资产、无形资产及递延资产、其他资产等，即为企业资产负债表的资产总计项。所谓流动性是指企业资产的变现能力和支付能力。该指标根据会计“资产负债表”中“资产总计”项的年末数填列。资产总计=流动资产+长期投资+固定资产+无形及递延资产+其他资产。'},
     42: {'source_key': 'shortterm_loan', 'save_key': 'st_borrow', 'data_type': 'decimal(20,4)', 'comment': '短期借款\n短期借款企业用来维持正常的生产经营所需的资金或为抵偿某项债务而向银行或其他金融机构等外单位借入的、还款期限在一年以下或者一年的一个经营周期内的各种借款。'},
     43: {'source_key': 'trading_liability', 'save_key': 'tradable_fin_liab', 'data_type': 'decimal(20,4)', 'comment': '交易性金融负债\n交易性金融负债是指企业采用短期获利模式进行融资所形成的负债，比如短期借款、长期借款、应付债券。作为交易双方来说，甲方的金融债权就是乙方的金融负债，由于融资方需要支付利息，因比，就形成了金融负债。交易性金融负债是企业承担的交易性金融负债的公允价值。'},
     44: {'source_key': 'notes_payable', 'save_key': 'notes_payable', 'data_type': 'decimal(20,4)', 'comment': '应付票据\n应付票据是指企业购买材料、商品和接受劳务供应等而开出、承兑的商业汇票，包括商业承兑汇票和银行承兑汇票。在我国应收票据、应付票据仅指“商业汇票”，包括“银行承兑汇票”和“商业承兑汇票”两种，属于远期票据，付款期一般在1个月以上，6个月以内。其他的银行票据（支票、本票、汇票）等，都是作为货币资金来核算的，而不作为应收应付票据。'},
     45: {'source_key': 'accounts_payable', 'save_key': 'acct_payable', 'data_type': 'decimal(20,4)', 'comment': '应付账款\n应付账款是指因购买材料、商品或接受劳务供应等而发生的债务，这是买卖双方在购销活动中由于取得物资与支付贷款在时间上不一致而产生的负债。'},
     46: {'source_key': 'advance_peceipts', 'save_key': 'adv_from_cust', 'data_type': 'decimal(20,4)', 'comment': '预收款项\n预收款项是在企业销售交易成立以前，预先收取的部分货款。'},
     47: {'source_key': 'salaries_payable', 'save_key': 'empl_ben_payable', 'data_type': 'decimal(20,4)', 'comment': '应付职工薪酬\n应付职工薪酬是指企业为获得职工提供的服务而给予各种形式的报酬以及其他相关支出。职工薪酬包括：职工工资、奖金、津贴和补贴；职工福利费；医疗保险费、养老保险费、失业保险费、工伤保险费和生育保险费等社会保险费；住房公积金；工会经费和职工教育经费；非货币性福利；因解除与职工的劳动关系给予的补偿；其他与获得职工提供的服务相关的支出。原“应付工资”和“应付福利费”取消，换成“应付职工薪酬”。'},
     48: {'source_key': 'taxs_payable', 'save_key': 'taxes_surcharges_payable', 'data_type': 'decimal(20,4)', 'comment': '应交税费\n应交税费是指企业根据在一定时期内取得的营业收入、实现的利润等，按照现行税法规定，采用一定的计税方法计提的应交纳的各种税费。应交税费包括企业依法交纳的增值税、消费税、营业税、所得税、资源税、土地增值税、城市维护建设税、房产税、土地使用税、车船税、教育费附加、矿产资源补偿费等税费，以及在上缴国家之前，由企业代收代缴的个人所得税等。'},
     49: {'source_key': 'interest_payable', 'save_key': 'int_payable', 'data_type': 'decimal(20,4)', 'comment': '应付利息\n应付利息是指金融企业根据存款或债券金额及其存续期限和规定的利率，按期计提应支付给单位和个人的利息。应付利息应按已计但尚未支付的金额入账。应付利息包括分期付息到期还本的长期借款、企业债券等应支付的利息。应付利息与应计利息的区别：应付利息属于借款,应计利息属于企业存款。'},
     50: {'source_key': 'dividend_payable', 'save_key': 'dvd_payable', 'data_type': 'decimal(20,4)', 'comment': '应付股利\n应付股利是指企业根据年度利润分配方案，确定分配的股利。是企业经董事会或股东大会，或类似机构决议确定分配的现金股利或利润。企业分配的股票股利，不通过“应付股利”科目核算。确定时借记“未分配利润”帐户，贷记“应付股利”帐户；实际支付时借记“应付股利”帐户，贷记“银行存款”帐户。'},
     51: {'source_key': 'other_payable', 'save_key': 'oth_payable', 'data_type': 'decimal(20,4)', 'comment': '其他应付款\n其他应付款是财务会计中的一个往来科目，通常情况下，该科目只核算企业应付其他单位或个人的零星款项，如应付经营租入固定资产和包装物的租金、存入保证金、应付统筹退休金等。'},
     52: {'source_key': 'affiliated_company_payable', 'save_key': 'aff_pay', 'data_type': 'decimal(20,4)', 'comment': '应付关联公司款\n'},
     53: {'source_key': 'non_current_liability_in_one_year', 'save_key': 'non_cur_liab_due_within_1y', 'data_type': 'decimal(20,4)', 'comment': '一年内到期的非流动负债\n是反映企业各种非流动负债在一年之内到期的金额，包括一年内到期的长期借款、长期应付款和应付债券。本项目应根据上述账户分析计算后填列。计入(收录)流动负债中。'},
     54: {'source_key': 'total_current_liability', 'save_key': 'tot_cur_liab', 'data_type': 'decimal(20,4)', 'comment': '流动负债合计\n流动负债合计是指企业在一年内或超过一年的一个营业周期内需要偿还的债务，包括短期借款、应付帐款、其他应付款、应付工资、应付福利费、未交税金和未付利润、其他应付款、预提费用等。'},
     55: {'source_key': 'longterm_loan', 'save_key': 'lt_borrow', 'data_type': 'decimal(20,4)', 'comment': '长期借款\n长期借款是指企业从银行或其他金融机构借入的期限在一年以上(不含一年)的借款。我国股份制企业的长期借款主要是向金融机构借人的各项长期性借款，如从各专业银行、商业银行取得的贷款；除此之外，还包括向财务公司、投资公司等金融企业借人的款项。'},
     56: {'source_key': 'bonds_payable', 'save_key': 'bonds_payable', 'data_type': 'decimal(20,4)', 'comment': '应付债券\n应付债券是指企业为筹集资金而对外发行的期限在一年以上的长期借款性质的书面证明，约定在一定期限内还本付息的一种书面承诺。'},
     57: {'source_key': 'longterm_account_payable', 'save_key': 'lt_payable', 'data_type': 'decimal(20,4)', 'comment': '长期应付款\n长期应付款是指企业除了长期借款和应付债券以外的长期负债，包括应付引进设备款、应付融资租入固定资产的租赁费等。'},
     58: {'source_key': 'specific_account_payable', 'save_key': 'specific_item_payable', 'data_type': 'decimal(20,4)', 'comment': '专项应付款\n专项应付款是企业接受国家拨入的具有专门用途的款项所形成的不需要以资产或增加其他负债偿还的负债。专项应付款指企业接受国家拨入的具有专门用途的拨款，如新产品试制费拨款、中间试验费拨款和重要科学研究补助费拨款等科技三项拨款等。'},
     59: {'source_key': 'estimate_liability', 'save_key': 'provisions', 'data_type': 'decimal(20,4)', 'comment': '预计负债\n预计负债是因或有事项可能产生的负债。根据或有事项准则的规定，与或有事项相关的义务同时符合以下三个条件的，企业应将其确认为负债：一是该义务是企业承担的现时义务；二是该义务的履行很可能导致经济利益流出企业，这里的“很可能”指发生的可能性为“大于50%，但小于或等于95%”；三是该义务的金额能够可靠地计量。'},
     60: {'source_key': 'deferred_tax_liability', 'save_key': 'deferred_tax_liab', 'data_type': 'decimal(20,4)', 'comment': '递延所得税负债\n递延所得税负债是指根据应纳税暂时性差异计算的未来期间应付所得税的金额；递延所得税资产和递延所得税负债是和暂时性差异相对应的，可抵减暂时性差异是将来可用来抵税的部分，是应该收回的资产，所以对应递延所得税资产；递延所得税负债是由应纳税暂时性差异产生的，对于影响利润的暂时性差异，确认的递延所得税负债应该调整“所得税费用”。'},
     61: {'source_key': 'total_non_current_liability', 'save_key': 'tot_non_cur_liab', 'data_type': 'decimal(20,4)', 'comment': '非流动负债合计\n流动负债合计是指企业在一年内或超过一年的一个营业周期内需要偿还的债务，包括短期借款、应付帐款、其他应付款、应付工资、应付福利费、未交税金和未付利润、其他应付款、预提费用等。'},
     62: {'source_key': 'total_liability', 'save_key': 'tot_liab', 'data_type': 'decimal(20,4)', 'comment': '负债合计\n负债合计是指企业所承担的能以，将以资产或劳务偿还的债务，偿还形式包括货币、资产或提供劳务。'},
     63: {'source_key': 'paidin_capital', 'save_key': 'cap_stk', 'data_type': 'decimal(20,4)', 'comment': '实收资本（或股本）\n实收资本是指企业的投资者按照企业章程或合同、协议的约定，实际投入企业的资本。我国实行的是注册资本制，因而，在投资者足额缴纳资本之后，企业的实收资本应该等于企业的注册资本。“实收资本”科目用于核算企业实际收到的投资人投入的资本。'},
     64: {'source_key': 'capital_reserve_fund', 'save_key': 'cap_rsrv', 'data_type': 'decimal(20,4)', 'comment': '资本公积\n资本公积金是在公司的生产经营之外，由资本、资产本身及其他原因形成的股东权益收入。股份公司的资本公积金，主要来源于的股票发行的溢价收入、接受的赠与、资产增值、因合并而接受其他公司资产净额等。其中，股票发行溢价是上市公司最常见、是最主要的资本公积金来源。'},
     65: {'source_key': 'specific_reserves', 'save_key': 'special_rsrv', 'data_type': 'decimal(20,4)', 'comment': '专项储备\n专项储备用于核算高危行业企业按照规定提取的安全生产费以及维持简单再生产费用等具有类似性质的费用。'},
     66: {'source_key': 'surplus_reserve_fund', 'save_key': 'surplus_rsrv', 'data_type': 'decimal(20,4)', 'comment': '盈余公积\n盈余公积是指企业按照规定从净利润中提取的各种积累资金。'},
     67: {'source_key': 'treasury_stock', 'save_key': 'less_tsy_stk', 'data_type': 'decimal(20,4)', 'comment': '库存股\n指股份有限公司已发行的股票，由于公司的重新回购或其他原因且不是为了注销的目的而由公司持有的股票。'},
     68: {'source_key': 'retained_profit', 'save_key': 'undistributed_profit', 'data_type': 'decimal(20,4)', 'comment': '未分配利润\n未分配利润是企业未作分配的利润。它在以后年度可继续进行分配，在未进行分配之前，属于所有者权益的组成部分。'},
     69: {'source_key': 'equities_parent_company_owners', 'save_key': 'tot_eqy_parent_comp', 'data_type': 'decimal(20,4)', 'comment': '归属于母公司所有者权益\n母公司股东权益反映的是母公司所持股份部分的所有者权益数，所有者权益合计是反映的是所有的股东包括母公司与少数股东一起100%的股东所持股份的总体所有者权益合计数。即所有者权益合计＝母公司股东权益合计母＋少数股东权益合计。'},
     70: {'source_key': 'minority_interests', 'save_key': 'minority_int', 'data_type': 'decimal(20,4)', 'comment': '少数股东权益\n少数股东权益简称少数股权,是反映除母公司以外的其他投资者在子公司中的权益，表示其他投资者在子公司所有者权益中所拥有的份额。在控股合并形式下，子公司股东权益中未被母公司持有部分。在母公司拥有子公司股份不足100%，即只拥有子公司净资产的部分产权时，子公司股东权益的一部分属于母公司所有，即多数股权，其余部分仍属外界其他股东所有，由于后者在子公司全部股权中不足半数，对子公司没有控制能力，故被称为少数股权。'},
     71: {'source_key': 'foreign_currency_report_conv_diff', 'save_key': 'cnvd_diff_foreign_curr_stat', 'data_type': 'decimal(20,4)', 'comment': '外币报表折算价差\n是指在编制合并财务报表时，把国外子公司或分支机构以所在国家货币编制的财务报表折算成以记账本位币表达的财务报表时，由于报表项目采用不同汇率折算而形成的汇兑损益。'},
     72: {'source_key': 'irregular_item_adjustment', 'save_key': 'irr_oper_rev_adj', 'data_type': 'decimal(20,4)', 'comment': '非正常经营项目收益调整\n'},
     73: {'source_key': 'total_owner_equities', 'save_key': 'tot_shrhldr_eqy_incl_min_int', 'data_type': 'decimal(20,4)', 'comment': '所有者权益（或股东权益）合计\n指股本、资本公积、盈余公积、未分配利润的之和，代表了股东对企业的所有权，反映了股东在企业资产中享有的经济利益。'},
     74: {'source_key': 'total_sheet_owner_equities', 'save_key': 'tot_liab_shrhldr_eqy', 'data_type': 'decimal(20,4)', 'comment': '负债和所有者权益（或股东权益）合计\n负债和股东权益总计是等于负债总额加上股东权益总额，也等于资产总额。'},
     75: {'source_key': 'other_comprehesive_income', 'save_key': 'oth_comp_inc', 'data_type': 'decimal(20,4)', 'comment': '其他综合收益\n'},
     76: {'source_key': 'deferred_earning', 'save_key': 'deferred_inc_non_cur_liab', 'data_type': 'decimal(20,4)', 'comment': '递延收益-非流动负债\n'},
     77: {'source_key': 'settlement_provi', 'save_key': 'settle_rsrv', 'data_type': 'decimal(20,4)', 'comment': '结算备付金\n结算备付金是指结算参与人根据规定，存放在其资金交收账户中用于证券交易及非交易结算的资金。资金交收账户即结算备付金账户。'},
     78: {'source_key': 'lend_capital', 'save_key': 'loans_to_oth_banks', 'data_type': 'decimal(20,4)', 'comment': '拆出资金\n企业（金融）拆借给境内、境外其他金融机构的款项。'},
     79: {'source_key': 'loan_and_advance_current_assets', 'save_key': 'loans_and_adv_granted_cur', 'data_type': 'decimal(20,4)', 'comment': '发放贷款及垫款-流动资产\n'},
     80: {'source_key': 'derivative_financial_asset', 'save_key': 'derivative_fin_assets', 'data_type': 'decimal(20,4)', 'comment': '衍生金融资产\n'},
     81: {'source_key': 'insurance_receivables', 'save_key': 'prem_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收保费\n保险公司按照合同约定应向投保人收取但尚未收到的保费收入。'},
     82: {'source_key': 'reinsurance_receivables', 'save_key': 'rcv_from_reinsurer', 'data_type': 'decimal(20,4)', 'comment': '应收分保账款\n指公司开展分保业务而发生的各种应收款项。'},
     84: {'source_key': 'bought_sellback_assets', 'save_key': 'red_monetary_cap_for_sale', 'data_type': 'decimal(20,4)', 'comment': '买入返售金融资产\n指公司按返售协议约定先买入再按固定价格返售的证券等金融资产所融出的资金。'},
     85: {'source_key': 'hold_sale_asset', 'save_key': 'hold_sale_asset', 'data_type': 'decimal(20,4)', 'comment': '划分为持有待售的资产\n'},
     86: {'source_key': 'loan_and_advance_noncurrent_assets', 'save_key': 'loans_and_adv_granted_non_cur', 'data_type': 'decimal(20,4)', 'comment': '发放贷款及垫款-非流动资产\n'},
     87: {'source_key': 'borrowing_from_centralbank', 'save_key': 'borrow_central_bank', 'data_type': 'decimal(20,4)', 'comment': '向中央银行借款\n向中央银行借款的形式有两种，一种是直接借款，也称再贷款;另一种为间接借款，即所谓的再贴现。'},
     88: {'source_key': 'deposit_in_interbank', 'save_key': 'deposit_received_ib_deposits', 'data_type': 'decimal(20,4)', 'comment': '吸收存款及同业存放\n吸收存款是负债类科目，它核算企业（银行）吸收的除了同业存放款项以外的其他各种存款，即：收到的除金融机构以外的企业或者个人、组织的存款，包括单位存款（企业、事业单位、机关、社会团体等）、个人存款、信用卡存款、特种存款、转贷款资金和财政性存款等。同业存放，也称同业存款，全称是同业及其金融机构存入款项，是指因支付清算和业务合作等的需要，由其他金融机构存放于商业银行的款项。'},
     89: {'source_key': 'borrowing_capital', 'save_key': 'loans_oth_banks', 'data_type': 'decimal(20,4)', 'comment': '拆入资金\n拆入资金，是指信托投资公司向银行或其他金融机构借入的资金。拆入资金应按实际借入的金额入账。'},
     90: {'source_key': 'derivative_financial_liability', 'save_key': 'derivative_fin_liab', 'data_type': 'decimal(20,4)', 'comment': '衍生金融负债\n'},
     91: {'source_key': 'sold_buyback_secu_proceeds', 'save_key': 'fund_sales_fin_assets_rp', 'data_type': 'decimal(20,4)', 'comment': '卖出回购金融资产款\n卖出回购金融资产款是用于核算企业（金融）按回购协议卖出票据、证券、贷款等金融资产所融入的资金。'},
     92: {'source_key': 'commission_payable', 'save_key': 'handling_charges_comm_payable', 'data_type': 'decimal(20,4)', 'comment': '应付手续费及佣金\n是会计科目的一种，用以核算企业因购买材料、商品和接受劳务供应等经营活动应支付的款项。通常是指因购买材料、商品或接受劳务供应等而发生的债务，这是买卖双方在购销活动中由于取得物资与支付贷款在时间上不一致而产生的负债。'},
     93: {'source_key': 'reinsurance_payables', 'save_key': 'payable_to_reinsurer', 'data_type': 'decimal(20,4)', 'comment': '应付分保账款\n应付分保账款表示债务，这样一来，债权、债务关系更加一目了然。另外，财产保险公司应收分保账款是指本公司与其他保险公司之间开展分保业务发生的各种应收款项。'},
     94: {'source_key': 'insurance_contract_reserves', 'save_key': 'rsrv_insur_cont', 'data_type': 'decimal(20,4)', 'comment': '保险合同准备金\n险准备金是指保险人为保证其如约履行保险赔偿或给付义务，根据政府有关法律规定或业务特定需要，从保费收入或盈余中提取的与其所承担的保险责任相对应的一定数量的基金。'},
     95: {'source_key': 'proxy_secu_proceeds', 'save_key': 'acting_trading_sec', 'data_type': 'decimal(20,4)', 'comment': '代理买卖证券款\n代理买卖证券款是指公司接受客户委托，代理客户买卖股票、债券和基金等有价证券而收到的款项，包括公司代理客户认购新股的款项、代理客户领取的现金股利和债券利息，代客户向证券交易所支付的配股款等。'},
     96: {'source_key': 'receivings_from_vicariously', 'save_key': 'acting_uw_sec', 'data_type': 'decimal(20,4)', 'comment': '代理承销证券款\n'},
     97: {'source_key': 'hold_sale_liability', 'save_key': 'hold_sale_liab', 'data_type': 'decimal(20,4)', 'comment': '划分为持有待售的负债\n'},
     98: {'source_key': 'estimate_liability_current', 'save_key': 'provisions_cur', 'data_type': 'decimal(20,4)', 'comment': '预计负债-流动负债\n'},
     99: {'source_key': 'deferred_earning_current', 'save_key': 'deferred_inc_cur_liab', 'data_type': 'decimal(20,4)', 'comment': '递延收益-流动负债\n'},
     100: {'source_key': 'preferred_shares_noncurrent', 'save_key': 'prfshare_non_cur', 'data_type': 'decimal(20,4)', 'comment': '优先股-非流动负债\n'},
     101: {'source_key': 'pepertual_liability_noncurrent', 'save_key': 'peper_liab_non_cur', 'data_type': 'decimal(20,4)', 'comment': '永续债-非流动负债\n'},
     102: {'source_key': 'longterm_salaries_payable', 'save_key': 'lt_empl_ben_payable', 'data_type': 'decimal(20,4)', 'comment': '长期应付职工薪酬\n'},
     103: {'source_key': 'other_equity_tools', 'save_key': 'oth_eqy_tool', 'data_type': 'decimal(20,4)', 'comment': '其他权益工具\n'},
     104: {'source_key': 'preferred_shares_equity', 'save_key': 'prfshare_eqy', 'data_type': 'decimal(20,4)', 'comment': '其中：优先股-所有者权益\n'},
     105: {'source_key': 'pepertual_liability_equity', 'save_key': 'peper_liab_eqy', 'data_type': 'decimal(20,4)', 'comment': '永续债-所有者权益\n'},
     106: {'source_key': 'other_current_assets', 'save_key': 'oth_cur_assets', 'data_type': 'decimal(20,4)', 'comment': '其他流动资产\n其他流动资产，是指除货币资金、短期投资、应收票据、应收账款、其他应收款、存货等流动资产以外的流动资产'},
     107: {'source_key': 'other_non_current_assets', 'save_key': 'oth_non_cur_assets', 'data_type': 'decimal(20,4)', 'comment': '其他非流动资产\n贷款是指贷款人(我国的商业银行等金融机构)对借款人提供的并按约定的利率和期限还本付息的货币资金。贷款币可以是人民币，也可以是外币。'},
     108: {'source_key': 'other_current_liability', 'save_key': 'oth_cur_liab', 'data_type': 'decimal(20,4)', 'comment': '其他流动负债\n其他流动负债是指不能归属于短期借款，应付短期债券券，应付票据，应付帐款，应付所得税，其他应付款，预收账款这七款项目的流动负债。但以上各款流动负债，其金额未超过流动负债合计金额百分之五者，得并入其他流动负债内。'},
     109: {'source_key': 'other_non_current_liability', 'save_key': 'oth_non_cur_liab', 'data_type': 'decimal(20,4)', 'comment': '其他非流动负债\n其他非流动负债项目是反映企业除长期借款、应付债券等项目以外的其他非流动负债。其他非流动负债项目应根据有关科目的期末余额填列。其他非流动负债项目应根据有关科目期末余额减去将于一年内(含一年)到期偿还数后的余额填列。非流动负债各项目中将于一年内(含一年)到期的非流动负债，应在”一年内到期的非流动负债”项目内单独反映。'},
     110: {'source_key': 'ordinary_risk_reserve_fund', 'save_key': 'prov_nom_risks', 'data_type': 'decimal(20,4)', 'comment': '一般风险准备\n指从事证券业务的金融企业按规定从 净利润中提取，用于弥补亏损的 风险准备。'},
     111: {'source_key': 'contract_assets', 'save_key': 'cont_assets', 'data_type': 'decimal(20,4)', 'comment': '合同资产\n'},
     112: {'source_key': 'bond_invest', 'save_key': 'bond_invest', 'data_type': 'decimal(20,4)', 'comment': '债权投资\n'},
     113: {'source_key': 'other_bond_invest', 'save_key': 'oth_bond_invest', 'data_type': 'decimal(20,4)', 'comment': '其他债权投资\n'},
     114: {'source_key': 'other_equity_tools_invest', 'save_key': 'other_eqy_tools_invest', 'data_type': 'decimal(20,4)', 'comment': '其他权益工具投资\n'},
     115: {'source_key': 'other_non_current_financial_assets', 'save_key': 'oth_eqy_cur_fin_assets', 'data_type': 'decimal(20,4)', 'comment': '其他非流动金融资产\n'},
     116: {'source_key': 'contract_liability', 'save_key': 'cont_liab', 'data_type': 'decimal(20,4)', 'comment': '合同负债\n'},
     117: {'source_key': 'receivable_fin', 'save_key': 'rcv_fnc', 'data_type': 'decimal(20,4)', 'comment': '应收款项融资\n'},
     118: {'source_key': 'usufruct_assets', 'save_key': 'usufruct_assets', 'data_type': 'decimal(20,4)', 'comment': '使用权资产\n'},
     119: {'source_key': 'bill_and_account_payable', 'save_key': 'notes_acct_payable', 'data_type': 'decimal(20,4)', 'comment': '应付票据及应付账款\n'},
     120: {'source_key': 'bill_and_account_receivable', 'save_key': 'notes_acct_rcv', 'data_type': 'decimal(20,4)', 'comment': '应收票据及应收账款\n'},
     121: {'source_key': 'pubDate', 'save_key': nan, 'data_type': 'datetime', 'comment': '公告日期\n公司发布财报的日期'},
     122: {'source_key': 'statDate', 'save_key': nan, 'data_type': 'datetime', 'comment': '报告期\n财报统计的季度的最后一天, 比如2015-03-31, 2015-06-30'},
     123: {'source_key': 'reinsurance_contract_reserves_receivable', 'save_key': 'rcv_from_ceded_insur_cont_rsrv', 'data_type': 'decimal(20,4)', 'comment': '应收分保合同准备金(元)\n是用于核算企业（再保险分出人）从事再保险业务确认的应收分保未到期责任准备金，以及应向再保险接受人摊回的保险责任准备金。'},
     124: {'source_key': 'loan_and_advance', 'save_key': 'loans_and_adv_granted', 'data_type': 'decimal(20,4)', 'comment': '发放委托贷款及垫款(元)\n委托贷款是指由委托人提供合法来源的资金转入委托银行一般委存账户，委托银行根据委托人确定的贷款对象、用途、金额、期限、利率等代为发放、监督使用并协助收回的贷款业务。垫款是指银行在客户无力支付到期款项的情况下，被迫以自有资金代为支付的行为。'},
     125: {'source_key': 'receivings_from_vicariously_sold_securities', 'save_key': 'acting_uw_sec', 'data_type': 'decimal(20,4)', 'comment': '代理承销证券款(元)\n代理承销证券款是指公司接受委托，采用承购包销方式或代销方式承销证券所形成的、应付证券发行人的承销资金。'}}

class main():
    information = pd.DataFrame(df).T.dropna()
    params = {'table':'asharebalancesheet', 
              'columns': {j['save_key'].upper(): j[2:].to_list() for i,j in information.iterrows()}, 
              'primary': 'UNIQUE_KEY', 
              'keys': ['ANN_DT', 'REPORT_PERIOD']}



