# -*- coding: utf-8 -*-
"""
Created on Wed Aug  4 16:12:07 2021

@author: Porco Rosso
"""

from numpy import nan
import pandas as pd
df = {
     0: {'source_key': 'code', 'save_key': 's_info_windcode', 'data_type': 'varchar(12)', 'comment': '股票代码\n'},
     1: {'source_key': 'a_code', 'save_key': nan, 'data_type': 'varchar(12)', 'comment': 'A股代码\n'},
     2: {'source_key': 'b_code', 'save_key': nan, 'data_type': 'varchar(12)', 'comment': 'B股代码\n'},
     3: {'source_key': 'h_code', 'save_key': nan, 'data_type': 'varchar(12)', 'comment': 'H股代码\n'},
     4: {'source_key': 'pub_date', 'save_key': 'ann_dt', 'data_type': 'datetime', 'comment': '公告日期\n'},
     5: {'source_key': 'start_date', 'save_key': nan, 'data_type': 'datetime', 'comment': '开始日期\n'},
     6: {'source_key': 'end_date', 'save_key': nan, 'data_type': 'datetime', 'comment': '截止日期\n'},
     7: {'source_key': 'report_date', 'save_key': 'report_period', 'data_type': 'datetime', 'comment': '报告期\n'},
     8: {'source_key': 'id', 'save_key': 'id_key', 'data_type': 'int', 'comment': '来源自增ID\n'},
     9: {'source_key': 'source_id', 'save_key': nan, 'data_type': 'int', 'comment': '报表来源编码\n'},
     10: {'source_key': 'source', 'save_key': nan, 'data_type': 'varchar(60)', 'comment': '报表来源\n'},
     11: {'source_key': 'goods_sale_and_service', 'save_key': 'cash_recp_sg_and_rs', 'data_type': 'decimal(20,4)', 'comment': '销售商品、提供劳务收到的现金\n反映企业本期销售商品、提供劳务收到的现金，以及前期销售商品、提供劳务本期收到的现金（包括销售收入和应向购买者收取的增值税销项税额）和本期预收的款项，减去本期销售本期退回的商品和前期销售本期退回的商品支付的现金。企业销售材料和代购代销业务收到的现金，也在本项目反映。'},
     12: {'source_key': 'tax_levy_refund', 'save_key': 'recp_tax_rends', 'data_type': 'decimal(20,4)', 'comment': '收到的税费返还\n反映企业收到返还的增值税、营业税、所得税、消费税、关税和教育费附加返还款等各种税费。'},
     13: {'source_key': 'subtotal_operate_cash_inflow', 'save_key': 'stot_cash_inflows_oper_act', 'data_type': 'decimal(20,4)', 'comment': '经营活动现金流入小计\n销售商品、提供劳务+收到的现金收到的税费返还+收到其他与经营活动有关的现金。'},
     14: {'source_key': 'goods_and_services_cash_paid', 'save_key': 'cash_pay_goods_purch_serv_rec', 'data_type': 'decimal(20,4)', 'comment': '购买商品、接受劳务支付的现金\n反映企业本期购买商品、接受劳务实际支付的现金（包括增值税进项税额），以及本期支付前期购买商品、接受劳务的未付款项和本期预付款项，减去本期发生的购货退回收到的现金。'},
     15: {'source_key': 'staff_behalf_paid', 'save_key': 'cash_pay_beh_empl', 'data_type': 'decimal(20,4)', 'comment': '支付给职工以及为职工支付的现金\n这个项目反映企业实际支付给职工的现金以及为职工支付的现金，包括本期实际支付给职工的工资、奖金、各种津贴和补贴等，以及为职工支付的其他费用。不包括支付的离退休人员的各项费用和支付给在建工程人员的工资等。'},
     16: {'source_key': 'tax_payments', 'save_key': 'pay_all_typ_tax', 'data_type': 'decimal(20,4)', 'comment': '支付的各项税费\n反映企业本期发生并支付的、本期支付以前各期发生的以及预交的教育费附加、矿产资源补偿费、印花税、房产税、土地增值税、车船使用税、预交的营业税等税费，计入固定资产价值、实际支付的耕地占用税、本期退回的增值税、所得税等除外。'},
     17: {'source_key': 'subtotal_operate_cash_outflow', 'save_key': 'stot_cash_outflows_oper_act', 'data_type': 'decimal(20,4)', 'comment': '经营活动现金流出小计\n购买商品、接受劳务支付的现金+支付给职工以及为职工支付的现金+支付的各项税费+支付其他与经营活动有关的现金。'},
     18: {'source_key': 'net_operate_cash_flow', 'save_key': 'net_cash_flows_oper_act', 'data_type': 'decimal(20,4)', 'comment': '经营活动现金流量净额\n公式: 经营活动产生的现金流量净额'},
     19: {'source_key': 'invest_withdrawal_cash', 'save_key': 'cash_recp_disp_withdrwl_invest', 'data_type': 'decimal(20,4)', 'comment': '收回投资收到的现金\n反映企业出售、转让或到期收回除现金等价物以外的交易性金融资产、长期股权投资而收到的现金，以及收回长期债权投资本金而收到的现金，但长期债权投资收回的利息除外。'},
     20: {'source_key': 'invest_proceeds', 'save_key': 'cash_recp_return_invest', 'data_type': 'decimal(20,4)', 'comment': '取得投资收益收到的现金\n反映企业因股权性投资而分得的现金股利，从子公司、联营企业或合营企业分回利润而收到的现金，以及因债权性投资而取得的现金利息收入，但股票股利除外。'},
     21: {'source_key': 'fix_intan_other_asset_dispo_cash', 'save_key': 'net_cash_recp_disp_fiolta', 'data_type': 'decimal(20,4)', 'comment': '处置固定资产、无形资产和其他长期资产收回的现金净额\n反映企业出售、报废固定资产、无形资产和其他长期资产所取得的现金（包括因资产毁损而收到的保险赔偿收入），减去为处置这些资产而支付的有关费用后的净额，但现金净额为负数的除外。'},
     22: {'source_key': 'net_cash_deal_subcompany', 'save_key': 'net_cash_recp_disp_sobu', 'data_type': 'decimal(20,4)', 'comment': '处置子公司及其他营业单位收到的现金净额\n反映企业处置子公司及其他营业单位所取得的现金减去相关处置费用后的净额。'},
     23: {'source_key': 'subtotal_invest_cash_inflow', 'save_key': 'stot_cash_inflows_inv_act', 'data_type': 'decimal(20,4)', 'comment': '投资活动现金流入小计\n取得投资收益收到的现金+处置固定资产、无形资产和其他长期资产收回的现金净额+处置子公司及其他营业单位收到的现金净额+收到其他与投资活动有关的现金。'},
     24: {'source_key': 'fix_intan_other_asset_acqui_cash', 'save_key': 'cash_pay_acq_const_fiolta', 'data_type': 'decimal(20,4)', 'comment': '购建固定资产、无形资产和其他长期资产支付的现金\n反映企业购买、建造固定资产、取得无形资产和其他长期资产所支付的现金及增值税款、支付的应由在建工程和无形资产负担的职工薪酬现金支出，但为购建固定资产而发生的借款利息资本化部分、融资租入固定资产所支付的租赁费除外。'},
     25: {'source_key': 'invest_cash_paid', 'save_key': 'cash_paid_invest', 'data_type': 'decimal(20,4)', 'comment': '投资支付的现金\n反映企业取得的除现金等价物以外的权益性投资和债权性投资所支付的现金以及支付的佣金、手续费等附加费用。'},
     26: {'source_key': 'impawned_loan_net_increase', 'save_key': 'net_incr_pledge_loan', 'data_type': 'decimal(20,4)', 'comment': '质押贷款净增加额\n质押贷款是指贷款人按《担保法》规定的质押方式以借款人或第三人的动产或权利为质押物发放的贷款。'},
     27: {'source_key': 'net_cash_from_sub_company', 'save_key': 'net_cash_pay_aquis_sobu', 'data_type': 'decimal(20,4)', 'comment': '取得子公司及其他营业单位支付的现金净额\n反映企业购买子公司及其他营业单位购买出价中以现金支付的部分，减去子公司或其他营业单位持有的现金和现金等价物后的净额。'},
     28: {'source_key': 'subtotal_invest_cash_outflow', 'save_key': 'stot_cash_outflows_inv_act', 'data_type': 'decimal(20,4)', 'comment': '投资活动现金流出小计\n购建固定资产、无形资产和其他长期资产支付的现金+投资支付的现金+取得子公司及其他营业单位支付的现金净额+支付其他与投资活动有关的现金。'},
     29: {'source_key': 'net_invest_cash_flow', 'save_key': 'net_cash_flows_inv_act', 'data_type': 'decimal(20,4)', 'comment': '投资活动现金流量净额\n现金流量表科目。'},
     30: {'source_key': 'cash_from_invest', 'save_key': 'cash_recp_cap_contrib', 'data_type': 'decimal(20,4)', 'comment': '吸收投资收到的现金\n反映企业以发行股票、债券等方式筹集资金实际收到的款项，减去直接支付给金融企业的佣金、手续费、宣传费、咨询费、印刷费等发行费用后的净额。'},
     31: {'source_key': 'cash_from_borrowing', 'save_key': 'cash_recp_borrow', 'data_type': 'decimal(20,4)', 'comment': '取得借款收到的现金\n反映企业举借各种短期、长期借款而收到的现金。'},
     32: {'source_key': 'cash_from_bonds_issue', 'save_key': 'proc_issue_bonds', 'data_type': 'decimal(20,4)', 'comment': '发行债券收到的现金\n反映商业银行本期发行债券收到的本金。'},
     33: {'source_key': 'subtotal_finance_cash_inflow', 'save_key': 'stot_cash_inflows_fnc_act', 'data_type': 'decimal(20,4)', 'comment': '筹资活动现金流入小计\n吸收投资收到的现金+取得借款收到的现金+收到其他与筹资活动有关的现金+发行债券收到的现金。'},
     34: {'source_key': 'borrowing_repayment', 'save_key': 'cash_prepay_amt_borr', 'data_type': 'decimal(20,4)', 'comment': '偿还债务支付的现金\n反映企业以现金偿还债务的本金。'},
     35: {'source_key': 'dividend_interest_payment', 'save_key': 'cash_pay_dist_dpcp_int_exp', 'data_type': 'decimal(20,4)', 'comment': '分配股利、利润或偿付利息支付的现金\n反映企业实际支付的现金股利、支付给其他投资单位的利润或用现金支付的借款利息、债券利息。'},
     36: {'source_key': 'subtotal_finance_cash_outflow', 'save_key': 'stot_cash_outflows_fnc_act', 'data_type': 'decimal(20,4)', 'comment': '筹资活动现金流出小计\n现金流量表科目。'},
     37: {'source_key': 'net_finance_cash_flow', 'save_key': 'net_cash_flows_fnc_act', 'data_type': 'decimal(20,4)', 'comment': '筹资活动现金流量净额\n现金流量表科目。'},
     38: {'source_key': 'exchange_rate_change_effect', 'save_key': 'eff_fx_flu_cash', 'data_type': 'decimal(20,4)', 'comment': '汇率变动对现金的影响\n指企业外币现金流量及境外子公司的现金流量折算成记账本位币时，所采用的是现金流量发生日的汇率或即期汇率的近似汇率。'},
     39: {'source_key': 'other_reason_effect_cash', 'save_key': 'other_reason_effect_cash', 'data_type': 'decimal(20,4)', 'comment': '其他原因对现金的影响\n'},
     40: {'source_key': 'cash_equivalent_increase', 'save_key': 'net_incr_cash_cash_equ', 'data_type': 'decimal(20,4)', 'comment': '现金及现金等价物净增加额\n中外币现金净增加额按期末汇率折算的金额。'},
     41: {'source_key': 'cash_equivalents_at_beginning', 'save_key': 'cash_cash_equ_beg_period', 'data_type': 'decimal(20,4)', 'comment': '期初现金及现金等价物余额\n现金流量表科目。'},
     42: {'source_key': 'cash_and_equivalents_at_end', 'save_key': 'cash_cash_equ_end_period', 'data_type': 'decimal(20,4)', 'comment': '期末现金及现金等价物余额\n现金流量表科目。'},
     43: {'source_key': 'net_profit', 'save_key': 'net_profit_cash_sheet', 'data_type': 'decimal(20,4)', 'comment': '净利润\n'},
     44: {'source_key': 'assets_depreciation_reserves', 'save_key': 'plus_prov_depr_assets', 'data_type': 'decimal(20,4)', 'comment': '资产减值准备\n'},
     45: {'source_key': 'fixed_assets_depreciation', 'save_key': 'depr_fa_coga_dpba', 'data_type': 'decimal(20,4)', 'comment': '固定资产折旧、油气资产折耗、生产性生物资产折旧\n'},
     46: {'source_key': 'intangible_assets_amortization', 'save_key': 'amort_intang_assets', 'data_type': 'decimal(20,4)', 'comment': '无形资产摊销\n'},
     47: {'source_key': 'defferred_expense_amortization', 'save_key': 'amort_lt_deferred_exp', 'data_type': 'decimal(20,4)', 'comment': '长期待摊费用摊销\n'},
     48: {'source_key': 'fix_intan_other_asset_dispo_loss', 'save_key': 'loss_disp_fiolta', 'data_type': 'decimal(20,4)', 'comment': '处置固定资产、无形资产和其他长期资产的损失\n'},
     49: {'source_key': 'fixed_asset_scrap_loss', 'save_key': 'loss_scr_fa', 'data_type': 'decimal(20,4)', 'comment': '固定资产报废损失\n'},
     50: {'source_key': 'fair_value_change_loss', 'save_key': 'loss_fv_chg', 'data_type': 'decimal(20,4)', 'comment': '公允价值变动损失\n'},
     51: {'source_key': 'financial_cost', 'save_key': 'fin_exp', 'data_type': 'decimal(20,4)', 'comment': '财务费用\n'},
     52: {'source_key': 'invest_loss', 'save_key': 'invest_loss', 'data_type': 'decimal(20,4)', 'comment': '投资损失\n'},
     53: {'source_key': 'deffered_tax_asset_decrease', 'save_key': 'decr_deferred_inc_tax_assets', 'data_type': 'decimal(20,4)', 'comment': '递延所得税资产减少\n'},
     54: {'source_key': 'deffered_tax_liability_increase', 'save_key': 'incr_deferred_inc_tax_liab', 'data_type': 'decimal(20,4)', 'comment': '递延所得税负债增加\n'},
     55: {'source_key': 'inventory_decrease', 'save_key': 'decr_inventories', 'data_type': 'decimal(20,4)', 'comment': '存货的减少\n'},
     56: {'source_key': 'operate_receivables_decrease', 'save_key': 'decr_oper_payable', 'data_type': 'decimal(20,4)', 'comment': '经营性应收项目的减少\n'},
     57: {'source_key': 'operate_payable_increase', 'save_key': 'incr_oper_payable', 'data_type': 'decimal(20,4)', 'comment': '经营性应付项目的增加\n'},
     58: {'source_key': 'others', 'save_key': 'others', 'data_type': 'decimal(20,4)', 'comment': '其他\n'},
     59: {'source_key': 'net_operate_cash_flow_indirect', 'save_key': 'im_net_cash_flows_oper_act', 'data_type': 'decimal(20,4)', 'comment': '经营活动现金流量净额_间接法\n'},
     60: {'source_key': 'debt_to_capital', 'save_key': 'conv_debt_into_cap', 'data_type': 'decimal(20,4)', 'comment': '债务转为资本\n'},
     61: {'source_key': 'cbs_expiring_in_one_year', 'save_key': 'conv_corp_bonds_due_within_1y', 'data_type': 'decimal(20,4)', 'comment': '一年内到期的可转换公司债券\n'},
     62: {'source_key': 'financial_lease_fixed_assets', 'save_key': 'fa_fnc_leases', 'data_type': 'decimal(20,4)', 'comment': '融资租入固定资产\n'},
     63: {'source_key': 'cash_at_end', 'save_key': 'end_bal_cash', 'data_type': 'decimal(20,4)', 'comment': '现金的期末余额\n'},
     64: {'source_key': 'cash_at_beginning', 'save_key': 'less_beg_bal_cash', 'data_type': 'decimal(20,4)', 'comment': '现金的期初余额\n'},
     65: {'source_key': 'equivalents_at_end', 'save_key': 'plus_end_bal_cash_equ', 'data_type': 'decimal(20,4)', 'comment': '现金等价物的期末余额\n'},
     66: {'source_key': 'equivalents_at_beginning', 'save_key': 'less_beg_bal_cash_equ', 'data_type': 'decimal(20,4)', 'comment': '现金等价物的期初余额\n'},
     67: {'source_key': 'other_reason_effect_cash_indirect', 'save_key': 'oth_effect_cash_indirect', 'data_type': 'decimal(20,4)', 'comment': '其他原因对现金的影响_间接法\n'},
     68: {'source_key': 'cash_equivalent_increase_indirect', 'save_key': 'im_net_incr_cash_cash_equ', 'data_type': 'decimal(20,4)', 'comment': '现金及现金等价物净增加额_间接法\n'},
     69: {'source_key': 'net_deposit_increase', 'save_key': 'net_incr_dep_cob', 'data_type': 'decimal(20,4)', 'comment': '客户存款和同业存放款项净增加额\n客户存款和同业存款净增加额=客户存款和同业存款期末余额－客户存款和同业存款期初余额。'},
     70: {'source_key': 'net_borrowing_from_central_bank', 'save_key': 'net_incr_loans_central_bank', 'data_type': 'decimal(20,4)', 'comment': '向中央银行借款净增加额\n向中央银行借款净增加额=向中央银行借款期末余额－向中央银行借款期初余额。'},
     71: {'source_key': 'net_borrowing_from_finance_co', 'save_key': 'net_incr_fund_borr_ofi', 'data_type': 'decimal(20,4)', 'comment': '向其他金融机构拆入资金净增加额\n向其他金融机构拆入资金净增加额=向其他金融机构拆入资金期末余额－向其他金融机构拆入资金期初余额。'},
     72: {'source_key': 'net_original_insurance_cash', 'save_key': 'cash_recp_prem_orig_inco', 'data_type': 'decimal(20,4)', 'comment': '收到原保险合同保费取得的现金\n收到原保险合同保费取得的现金'},
     73: {'source_key': 'net_cash_received_from_reinsurance_business', 'save_key': 'net_cash_received_reinsu_bus', 'data_type': 'decimal(20,4)', 'comment': '收到再保险业务现金净额\n再保险是指一个保险人，分出一定的保险金额给另一个保险人。'},
     74: {'source_key': 'net_insurer_deposit_investment', 'save_key': 'net_incr_insured_dep', 'data_type': 'decimal(20,4)', 'comment': '保户储金及投资款净增加额\n保户储金，是指保险公司以储金利息作为保费的保险业务，收到保户缴存的储金。投资款是收到股东的款项。'},
     75: {'source_key': 'net_deal_trading_assets', 'save_key': 'net_gain_chg_fv', 'data_type': 'decimal(20,4)', 'comment': '处置以公允价值计量且其变动计入当期损益的金融资产净增加额\n交易性金融资产是指企业为了近期内出售而持有的债券投资、股票投资和基金投资。'},
     76: {'source_key': 'interest_and_commission_cashin', 'save_key': 'net_incr_int_handling_chrg', 'data_type': 'decimal(20,4)', 'comment': '收取利息、手续费及佣金的现金\n收取利息、手续费及佣金的现金'},
     77: {'source_key': 'net_increase_in_placements', 'save_key': 'net_incr_loans_other_bank', 'data_type': 'decimal(20,4)', 'comment': '拆入资金净增加额\n拆入资金净增加额=拆入资金期末余额－拆入资金期初余额。'},
     78: {'source_key': 'net_buyback', 'save_key': 'net_incr_repurch_bus_fund', 'data_type': 'decimal(20,4)', 'comment': '回购业务资金净增加额\n回购交易是质押贷款的一种方式，通常用在政府债券上。债券经纪人向投资者临时出售一定的债券，同时签约在一定的时间内以稍高价格买回来。债券经纪人从中取得资金再用来投资，而投资者从价格差中得利。'},
     79: {'source_key': 'net_loan_and_advance_increase', 'save_key': 'net_incr_clients_loan_adv', 'data_type': 'decimal(20,4)', 'comment': '客户贷款及垫款净增加额\n客户贷款是科目核算信托项目管理运用、处分信托财产而持有的各项贷款。垫款是指银行在客户无力支付到期款项的情况下，被迫以自有资金代为支付的行为。'},
     80: {'source_key': 'net_deposit_in_cb_and_ib', 'save_key': 'net_incr_dep_cbob', 'data_type': 'decimal(20,4)', 'comment': '存放中央银行和同业款项净增加额\n存放中央银行款项是指各金融企业在中央银行开户而存入的用于支付清算、调拨款项、提取及缴存现金、往来资金结算以及按吸收存款的一定比例缴存于中央银行的款项和其他需要缴存的款项。存放同业是指商业银行存放在其他银行和非银行金融机构的存款。'},
     81: {'source_key': 'original_compensation_paid', 'save_key': 'cash_pay_claims_orig_inco', 'data_type': 'decimal(20,4)', 'comment': '支付原保险合同赔付款项的现金\n赔付支出主要指核算企业（保险）支付的原保险合同赔付款项和再保险合同赔付款项。原保险即是区别于再保险的名词。'},
     82: {'source_key': 'handling_charges_and_commission', 'save_key': 'handling_chrg_paid', 'data_type': 'decimal(20,4)', 'comment': '支付利息、手续费及佣金的现金\n一般是指涉及到贷款利息，银行扣缴的手续费及佣金等现金的流出，用在利息指出，或者银行手续费支出，佣金支出等业务上。'},
     83: {'source_key': 'policy_dividend_cash_paid', 'save_key': 'comm_insur_plcy_paid', 'data_type': 'decimal(20,4)', 'comment': '支付保单红利的现金\n保单红利支出是根据原保险合同的约定，按照分红保险产品的红利分配方法及有关精算结果而估算，支付给保单持有人的红利。'},
     84: {'source_key': 'cash_from_mino_s_invest_sub', 'save_key': 'incl_cash_rec_saims', 'data_type': 'decimal(20,4)', 'comment': '子公司吸收少数股东投资收到的现金\n《企业会计准则第33 号——合并财务报表》合并现金流量表科目。具体核算范围和方法参见上市公司定期报告。'},
     85: {'source_key': 'proceeds_from_sub_to_mino_s', 'save_key': 'incl_dvd_profit_paid_sc_ms', 'data_type': 'decimal(20,4)', 'comment': '子公司支付给少数股东的股利、利润\n一般企业现金流量表科目。'},
     86: {'source_key': 'investment_property_depreciation', 'save_key': 'investment_property_depreciation', 'data_type': 'decimal(20,4)', 'comment': '投资性房地产的折旧及摊销\n'},
     87: {'source_key': 'credit_impairment_loss', 'save_key': 'credit_impairment_loss_cash_sheet', 'data_type': 'decimal(20,4)', 'comment': '信用减值损失(现金流量表补充科目)\n'},
     88: {'source_key': 'other_cashin_related_operate', 'save_key': 'other_cash_recp_ral_oper_act', 'data_type': 'decimal(20,4)', 'comment': '收到其他与经营活动有关的现金(元)\n反映企业收到的罚款收入、经营租赁收到的租金等其他与经营活动有关的现金流入，金额较大的应当单独列示。'},
     89: {'source_key': 'other_operate_cash_paid', 'save_key': 'other_cash_pay_ral_oper_act', 'data_type': 'decimal(20,4)', 'comment': '支付其他与经营活动有关的现金(元)\n反映企业支付的罚款支出、支付的差旅费、业务招待费、保险费、经营租赁支付的现金等其他与经营活动有关的现金流出，金额较大的应当单独列示。'},
     90: {'source_key': 'other_cash_from_invest_act', 'save_key': 'other_cash_recp_ral_inv_act', 'data_type': 'decimal(20,4)', 'comment': '收到其他与投资活动有关的现金(元)\n反映企业除上述各项目外收到或支付的其他与投资活动有关的现金流入或流出，金额较大的应当单独列示。'},
     91: {'source_key': 'other_cash_to_invest_act', 'save_key': 'other_cash_pay_ral_inv_act', 'data_type': 'decimal(20,4)', 'comment': '支付其他与投资活动有关的现金(元)\n现金流量表科目。'},
     92: {'source_key': 'other_finance_act_cash', 'save_key': 'other_cash_recp_ral_fnc_act', 'data_type': 'decimal(20,4)', 'comment': '收到其他与筹资活动有关的现金(元)\n反映企业除上述项目外，收到或支付的其他与筹资活动有关的现金流入或流出，包括以发行股票、债券等方式筹集资金而由企业直接支付的审计和咨询等费用、为购建固定资产而发生的借款利息资本化部分、融资租入固定资产所支付的租赁费、以分期付款方式购建固定资产以后各期支付的现金等。'},
     93: {'source_key': 'other_finance_act_payment', 'save_key': 'other_cash_pay_ral_fnc_act', 'data_type': 'decimal(20,4)', 'comment': '支付其他与筹资活动有关的现金(元)\n包括：筹资费用所支付的现金，融资租赁所支付的现金，减少注册资本所支付的现金（收购本公司股票、退还联营单位的联营投资等）企业以分期付款方式构建固定资产除首期付款支付的现金以外的其他各期所支付的现金。'}}


class main():
    information = pd.DataFrame(df).T.dropna()
    params = {'table':'asharecashflow', 
              'columns': {j['save_key'].upper(): j[2:].to_list() for i,j in information.iterrows()}, 
              'primary': 'UNIQUE_KEY', 
              'keys': ['ANN_DT', 'REPORT_PERIOD']}



